### ISSUE TITLE
Issue with the Delegates_Protocols (Starter) Branch

### ISSUE THREAD

**Issue by Sayum24** [EMacco/ios-tutorials#1]
The `SwitchViewController` and `MainViewController` were not 'imported' so I had to add them manually to the project.
And the `SwitchViewController`-File doesn't look like in your [video](https://youtu.be/HtU6yZbtCAQ).
The branch I'm talking about: https://github.com/EMacco/ios-tutorials/tree/delegate-protocol-starter/Delegates_Protocols
___
Edit:
It seems like the branch [delegate-protocol-complete](https://github.com/EMacco/ios-tutorials/tree/delegate-protocol-complete/Delegates_Protocols) is alright.

**Comment by EMacco** [comment]
Thank you very much for letting me know @Sayum24 
I've pushed what I believe is the correct Starter Project. 
Please let me know if this solves this issue? 🙏🏽

**Comment by Sayum24** [comment]
Yes, now the code looks like in your video.
Thank you for your content, it really helps me learning iOS-Development. 🙏🏽

**Comment by EMacco** [comment]
I'm really glad to hear it. ❤️‍🔥
